### ISSUE TITLE
sprint bug

### ISSUE THREAD

**Issue by dok441** [Tommy228/TTT_Spectator_Deathmatch#72]
My server is sprint and sometimes, the speed in dm, can either increase, if you spentwash before death or will slow down much if you went slowly. Before such was not, after the update DM.

GitHub master version used

**Comment by MinIsMin** [comment]
From what I understand you want to say:
> If I walk slowly or run before dying the default speed in the Spectator Deathmatch is changed.

On a newly installed server without any addons it is working correctly.
You're only slowed in Spectator Deathmatch [when zooming with a weapon](https://github.com/Tommy228/TTT_Spectator_Deathmatch/commit/4e7329015617a33b5e2866adbece66ad0c5f107a#diff-8ba15410f943f2cbee527ee6b9e0b64cR61).

Or do you use a sprint addon? If so, please post an URL.

You can also write in Russian, I have a friend who understands it.

**Comment by dok441** [comment]
Да, я использую спринт, вот код https://pastebin.com/vjKEaHB1

**Comment by dok441** [comment]
Скорость может меняться в положительную сторону и в отрицательную.

**Comment by MinIsMin** [comment]
Это потому, что вы переписываете «SetSpeed».
Лучше использовать крючок, но это должно исправить:

этот код перед кодом в функции «PMetaSetSpeed»:
`if self.IsGhost and self:IsGhost() then return end`

Помещая это до того, как код в функциях «KeyPress» и «KeyRelease» не повредит:
`if ply.IsGhost and ply:IsGhost() then return end`



In English:
It is because you overwrite 'SetSpeed'.
It would be better using a hook but this should fix it:

this code before the code in the function 'PMetaSetSpeed':
if self.IsGhost and self:IsGhost() then return end

Putting this before the code in the functions 'KeyPress' and 'KeyRelease' wouldn't hurt:
if ply.IsGhost and ply:IsGhost() then return end

**Comment by dok441** [comment]
It didn't help to fix it.
