### ISSUE TITLE
Conflict with TTT2/TTT2 Advanced Spectator Feature? Also Last Man Standing Issue?

### ISSUE THREAD

**Issue by mexikoedi** [Tommy228/TTT_Spectator_Deathmatch#88]
### What happened?
I'm getting "Something is creating Script Errors" and the "!lms" chat command works while i'm in the spectator deathmatch.

### Are there any lua errors in the console?
[ERROR] lua/cl_specdm_hud.lua:114: attempt to call method 'Draw' (a nil value)
  1. unknown - lua/cl_specdm_hud.lua:114

### Are you using a beta branch of GarrysMod? (No, prerelease, dev)
No.

### What version of TTT Spectator Deathmatch do you use? (e.g. Workshop, GitHub master, GitHub stable release)
Latest Workshop Version (22.01.2020)

-

My Collection that I am using on my TTT2 Server: https://steamcommunity.com/sharedfiles/filedetails/?id=1822673195
TTT2 Advanced Spectator Feature: https://steamcommunity.com/sharedfiles/filedetails/?id=1795338332
TTT2 Last Man Standing: https://steamcommunity.com/sharedfiles/filedetails/?id=1890611962

@P4sca1

**Comment by P4sca1** [comment]
@Alf21 Are the issue smentioned here fixed by #83 ?

**Comment by Alf21** [comment]
Since Tommy never decided merging this (with multiple hints), I stopped supporting this add-on because supporting a developing add-on that receives updates (and I need to contribute all the time the same changes) is useless. A version that is working with TTT2 should be available here: https://github.com/TheNickSkater/TTT_Spectator_Deathmatch
